#!/bin/bash -x

set -e

ABSOLUTE_PATH=$(readlink -f $0)
RSSMINER_CODE_ROOT="${ABSOLUTE_PATH%/*}"

cd server && make clean
cd $RSSMINER_CODE_ROOT
rake jstemple

FRONTEND_HOST=shenfeng.me
DEPLOYMENT_USER="deploy"
SSH_TARGET="${DEPLOYMENT_USER}@${FRONTEND_HOST}"
TARGET_DIR="/var/www/dict"

function remote_run {
    ssh "${SSH_TARGET}" "$1"
}

remote_run "sudo mkdir -p ${TARGET_DIR} && sudo chown deploy ${TARGET_DIR}"

rsync --rsh='ssh' -vr --delete --delete-excluded \
    --exclude-from conf/exclude.txt \
    "${RSSMINER_CODE_ROOT}/" "${SSH_TARGET}:${TARGET_DIR}/"

remote_run "sudo cp ${TARGET_DIR}/conf/shenfeng.me /etc/nginx/sites-available"
remote_run "cd ${TARGET_DIR}/server/ && make dist"
remote_run "cp ${TARGET_DIR}/server/dbdata /tmp"
remote_run 'kill -9 `pidof dict` || exit 0'
# remote_run 'nohup ${TARGET_DIR}/server/dict &'
remote_run "sudo service nginx restart"
