#!/bin/bash -x

set -e

ABSOLUTE_PATH=$(readlink -f $0)
DICT_CODE_ROOT="${ABSOLUTE_PATH%/*/*}"

cd server && make clean
cd $DICT_CODE_ROOT
rake jstemple
rake minify_js

HTML_FILE=`readlink -f  client/index.html`
CSS_FILE=`readlink -f  client/dict.css`
RESULT_FILE=`readlink -f client/dict.html`
cd ${DICT_CODE_ROOT}/src/java
javac me/shenfeng/CompressHtml.java
java me.shenfeng.CompressHtml $HTML_FILE $CSS_FILE dict-min.js $RESULT_FILE
rm me/shenfeng/CompressHtml.class
cd $DICT_CODE_ROOT
rm client/dict.html.gz -f
gzip -9 $RESULT_FILE

cd $DICT_CODE_ROOT

FRONTEND_HOST="106.187.91.68"
DEPLOYMENT_USER="deploy"
SSH_TARGET="${DEPLOYMENT_USER}@${FRONTEND_HOST}"
TARGET_DIR="/var/www/dict"

function remote_run {
    ssh "${SSH_TARGET}" "$1"
}

remote_run "sudo mkdir -p ${TARGET_DIR} && sudo chown deploy ${TARGET_DIR}"

rsync --rsh='ssh' -vr --delete --delete-excluded \
    --exclude-from conf/exclude.txt \
    "${DICT_CODE_ROOT}/" "${SSH_TARGET}:${TARGET_DIR}/"

remote_run "sudo cp ${TARGET_DIR}/conf/shenfeng.me /etc/nginx/sites-available"
remote_run "cd ${TARGET_DIR}/server/ && make dist"
# remote_run "cp ${TARGET_DIR}/server/dbdata /tmp"
remote_run "sudo cp ${TARGET_DIR}/scripts/dictionary /etc/init.d/"
remote_run "sudo chmod +x /etc/init.d/dictionary"
remote_run "sudo /etc/init.d/dictionary restart"
remote_run "sudo service nginx reload"

rm client/dict.html.gz -f
rm client/dict-min.js.gz -f
