#! /bin/bash
### BEGIN INIT INFO
# Provides:     rssminer
# Required-Stop:    $network $local_fs
# Should-Start:     $network $local_fs
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description:    rssminer, a web front end and backend
# Description:      rssminer, a web front end and backend
### END INIT INFO

AS_USER="deploy"

APP_NAME="dictionary"
APP_HOME="/var/www/dict"
PID_DIR="/var/run/${APP_NAME}"
LOG_DIR="/var/log/${APP_NAME}"

daemon_args="--name $APP_NAME \
    --respawn \
    --user $AS_USER \
    --pidfile $PID_DIR/pid \
    --stdout $LOG_DIR/output.log \
    --stderr $LOG_DIR/error.log \
    --chdir $APP_HOME/client"

function running() {
    daemon $daemon_args --running
}

function mkdir_chown() {
    mkdir -p $1
    chown $AS_USER $1
}

mkdir_chown $PID_DIR
mkdir_chown $LOG_DIR

function start_server() {
    if running; then
        echo "$APP_NAME already running."
        exit 0
    fi
    echo "Starting $APP_NAME"
    daemon $daemon_args -- $APP_HOME/server/dict
}

case "$1" in
    start)
        start_server;
        ;;
    stop)
        if ! running; then
            echo "$APP_NAME not running."
            exit 0
        fi
        echo "Stopping $APP_NAME"
        daemon $daemon_args --stop
        ;;
    status)
        if running; then
            echo "$APP_NAME running"
        else
            echo "$APP_NAME not running"
        fi
        ;;
    restart|force-reload)
        while running
        do
            $0 stop
            sleep 1;
        done
        $0 start
        ;;
    *)
        echo "Usage: /etc/init.d/$APP_NAME {start|status|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
